todoapp/todo/urls.py
from django.urls import path

from .views import index, detail, create ,edit, delete_item , create_item , edit_list , delete_list

app_name='todo'
urlpatterns = [
    path('', index, name='index'),
    path('<int:list_id>/', detail, name='list_details'),
    path('create/', create, name='list_create'),
    path('<int:list_id>/edit/<int:item_id>/',edit,name='item_edit'),
    path('<int:list_id>/delete/<int:item_id>/',delete_item,name='item_delete'),
    path('<int:list_id>/create/',create_item,name='item_create'),
    path('edit/<int:list_id>/', edit_list, name='list_edit'),
    path('delete/<int:list_id>/',delete_list,name='list_delete'),
]

todoapp/todoapp/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('todo.urls'))
]

todoapp/todo/models.py
from django.db import models
# Create your models here.

class TodoList(models.Model):

    list_name = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.list_name}"

class TodoItem(models.Model):

    title = models.CharField(max_length=100)
    checked = models.BooleanField(default=False)
    due_date = models.DateTimeField()

    todo_list = models.ForeignKey(to=TodoList, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.todo_list.list_name}: {self.title}"

todoapp/todo/views.py
from django.shortcuts import render , redirect
from django.http import HttpResponse, Http404
from django.template import loader

from .models import TodoList
from .models import TodoItem
from .form import form_item


# Create your views here.

def index(request):
    """Shows the Main page of todo-App containing Lists."""
    todolists = TodoList.objects.all()
    items = TodoItem.objects.all()
    template = loader.get_template('todo/index.html')
    context = {
        'todolists': todolists,
    }
    return render(request, 'todo/index.html', context)

def detail(request, list_id):
    try:
        todolist = TodoList.objects.get(id=list_id)
    except TodoList.DoesNotExist:
        raise Http404("This List Does not Exists")
    items_list = TodoItem.objects.filter(todo_list=todolist)
    context = {
        'todolist': todolist,
        'items_list': items_list
    }
    return render(request, 'todo/details.html', context)

def create(request):
    if request.method == "GET":
        return render(request, 'todo/createlist.html')

    name = request.POST["name"]
    if name:
        TodoList.objects.create(list_name=name)
        lists = TodoList.objects.all()
        context = {
            'todolists': lists,
        }  
        return render(request,'todo/index.html',context)
    else:
        raise Http404("Empty field")    

def edit(request,list_id,item_id):
    try:
        todoitem = TodoItem.objects.get(id=item_id)
    except TodoItem.DoesNotExist:
        raise Http404("This Item Does not Exists")
    form_data= form_item(instance=todoitem)
    if request.method == "POST":
        form_data=form_item(request.POST,instance=todoitem)
        if form_data.is_valid():
            form_data.save()
            return redirect(f'/todo/{list_id}')
        else:
            raise Http404("Invalid Inputs")        
    form = form_item()
    context = {
        "item" : form_data
    }
    return render(request, 'todo/edit.html', context)

def delete_item(request,list_id,item_id):
    try:
        todoitem = TodoItem.objects.get(id=item_id)
    except TodoItem.DoesNotExist:
        raise Http404("This Item Does not Exists")
    todoitem.delete()
    return redirect(f'/todo/{list_id}')

def create_item(request,list_id):
    todolist = TodoList.objects.get(id=list_id)
    if request.method == "POST":
        form_data=form_item(request.POST)
        if form_data.is_valid():
            object = form_data.save(commit=False)
            object.todo_list = todolist
            object.save()
            return redirect(f'/todo/{list_id}')
        else:
            raise Http404("Invalid Inputs")    
    form_data = form_item()
    context = {
        "item_for_add" : form_data
    }
    return render(request, 'todo/createitem.html', context)

def edit_list(request,list_id):
    try:
        todolist = TodoList.objects.get(id=list_id)
    except TodoList.DoesNotExist:
        raise Http404("This Item Does not Exists")
    if request.method == "GET":
        context ={
            'todo_list_name' : todolist,
        }
        return render(request, 'todo/editlist.html', context)

    name = request.POST["name"]
    if name:
        todolist.list_name = name
        todolist.save()
        lists = TodoList.objects.all()
        context = {
            'todolists': lists,
        }
        return render(request,'todo/index.html',context)   
    else:
        raise Http404("Empty field")
def delete_list(request , list_id):
    try:
        todolist = TodoList.objects.get(id=list_id)
    except TodoList.DoesNotExist:
        raise Http404("This List Does not Exists")
    if request.method == "GET":
        todolist.delete()
    return redirect(f"/todo/")

todoapp/todo/templates/todo/createitem.html
<form  method="post">
    {% csrf_token %}
    {{item_for_add}}
     <input type="submit">
    

</form>

todoapp/todo/templates/todo/createlist.html
<form action="{% url 'todo:list_create' %}" method="post">
    {% csrf_token %}
    <fieldset>
        <h1>Create New List</h1>
        <input type="text" name="name" id="name" required>
        <input type="submit">
    </fieldset>

</form>

todoapp/todo/templates/todo/details.html
<h1>{{todolist.list_name}}</h1>
<h2><a href="{%url 'todo:item_create' todolist.id %}">create a item</a></h2>
<ul>
    {% for item in items_list %}
    <li>
        {{item.title}}: {{item.due_date}}, {{item.checked}} <br><a href="{%url 'todo:item_edit' todolist.id item.id %}">EDIT</a><br><a href="{%url 'todo:item_delete' todolist.id item.id %}">DELETE</a>
    </li>
    
    {% endfor %}
</ul>

todoapp/todo/templates/todo/edit.html
<form  method="post">
    {% csrf_token %}
    {{item}}
     <input type="submit">
    

</form>

todoapp/todo/templates/todo/editlist.html
<form method="post">
    {% csrf_token %}
    <fieldset>
        <h1>edit list</h1>
        <input type="text" name="name" id="name" placeholder={{todo_list_name.list_name}}>
        <input type="submit">
    </fieldset>

</form>

todoapp/todo/templates/todo/index.html
<h1>TODO APP</h1>
<h2><a href="/todo/create">CREATE A LIST</a></h2>

{% if todolists %}

    <ul>
        {% for todolist in todolists %}
        <li><a href="/todo/{{todolist.id}}">{{todolist.list_name}}</a><br><a href="/todo/edit/{{todolist.id}}">edit</a><br><a href="/todo/delete/{{todolist.id}}">Delete</a></li>
        {% endfor %}
    </ul>

{% endif %}